# Generated by Django 4.1 on 2022-08-17 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notification_app', '0003_messgae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messgae',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messgae',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message', to=settings.AUTH_USER_MODEL),
        ),
    ]
