# Generated by Django 4.1 on 2022-08-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification_app', '0004_alter_messgae_sender_alter_messgae_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messgae',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created',)},
        ),
    ]
