# Generated by Django 4.1 on 2022-08-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_app', '0002_category_videotutorial_titel_videotutorial_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotutorial',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
