# Generated by Django 4.1 on 2022-08-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_app', '0009_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotutorial',
            name='like',
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='video_time',
            field=models.IntegerField(default=0),
        ),
    ]
