# Generated by Django 4.1 on 2022-08-17 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0015_delete_notification'),
        ('Tutorial_app', '0011_alter_videotutorial_video_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotutorial',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_tutorial', to='Acount_app.techer'),
        ),
    ]
