# Generated by Django 4.1 on 2022-08-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_app', '0013_alter_videotutorial_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotutorial',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
