# Generated by Django 4.1 on 2022-08-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0019_techer_slug'),
        ('Tutorial_app', '0015_alter_videotutorial_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotutorial',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tutorial', to='Acount_app.techer'),
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='titel',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
