# Generated by Django 4.1 on 2022-08-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_app', '0016_alter_videotutorial_teacher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videotutorial',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='منتشر شود؟'),
        ),
    ]
