# Generated by Django 4.1 on 2022-08-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_app', '0017_alter_videotutorial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotutorial',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
