# Generated by Django 4.1 on 2022-08-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_app', '0018_alter_videotutorial_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotutorial',
            name='special_video',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
