# Generated by Django 4.1 on 2022-08-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_app', '0019_videotutorial_special_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='video_time',
            field=models.TimeField(),
        ),
    ]
