# Generated by Django 4.1 on 2022-09-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_app', '0020_alter_comment_options_alter_videotutorial_video_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
    ]
