# Generated by Django 4.1 on 2022-09-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial_app', '0022_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotutorial',
            name='video_time',
            field=models.CharField(max_length=50, verbose_name='تایم ویدیو'),
        ),
    ]
