# Generated by Django 4.1 on 2022-08-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0004_user_image_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/assets/image/index.jpg', upload_to='user/image'),
        ),
    ]
