# Generated by Django 4.1 on 2022-08-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0014_notification_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
