# Generated by Django 4.1 on 2022-08-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0018_remove_techer_followers_techer_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='techer',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
