# Generated by Django 4.1 on 2022-08-28 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0024_rename_first_name_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 13, 20, 25, 692134, tzinfo=datetime.timezone.utc)),
        ),
    ]
