# Generated by Django 4.1 on 2022-09-04 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0030_rename_is_active_techer_is_activee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techer',
            old_name='is_activee',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 15, 36, 42, 818046, tzinfo=datetime.timezone.utc)),
        ),
    ]
