# Generated by Django 4.1 on 2022-09-04 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0031_rename_is_activee_techer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 15, 40, 33, 278121, tzinfo=datetime.timezone.utc)),
        ),
    ]
