# Generated by Django 4.1 on 2022-09-15 06:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acount_app', '0032_alter_user_special_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techer',
            options={'verbose_name': 'مدرس', 'verbose_name_plural': 'مدرس ها'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حساب های کاربری'},
        ),
        migrations.AlterField(
            model_name='techer',
            name='about_me',
            field=models.TextField(verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='techer',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='دنبال کننده ها'),
        ),
        migrations.AlterField(
            model_name='techer',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='مدرس فعال هست یا حیر؟'),
        ),
        migrations.AlterField(
            model_name='techer',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='teacher/cv', verbose_name='رزومه'),
        ),
        migrations.AlterField(
            model_name='techer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, default='defult/index.jpg', null=True, upload_to='user/image', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='کاربر فعال هست یا خیر؟'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='کاربر ادمین هست یا خیر؟'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='مدرس هست یا خیر؟'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 6, 7, 6, 935191, tzinfo=datetime.timezone.utc), verbose_name='کاربر خاص تا زمان:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, verbose_name='نام کاربری'),
        ),
    ]
